# Use the smallest possible official image as a base
FROM busybox:latest

# This Dockerfile does nothing else. It creates a tiny, empty image.
# We are using this to test if the multi-arch push itself is the problem,
# or if the problem is related to the contents of the original frontend image.
