# docker-compose.test.yml
# This file defines the isolated environment for running integration tests.

services:
  test-db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    # NOTE: We do NOT expose the port here.
    # pytest-docker will manage access to the container on a dynamic port,
    # preventing any conflicts with the development database.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
